#!/bin/sh
#
# Automatically start Emacs as a daemon if not started already.

. ~/bin/emacs.defs

LOCK=~/bin/lock-emacs

lockfile -0 -r 0 $LOCK > /dev/null 2>&1 || exit 0

if ! $CLIENT -e '"pass"' 2>&1 | grep '"pass"' > /dev/null; then
    echo "Starting Emacs daemon ..."
    $DAEMON --daemon
    echo "Starting Emacs daemon ... done"
fi

rm -f $LOCK
