#!/bin/sh
#
# Automatically start Emacs as a daemon if not started already.

. ~/emacs-shared/bin/emacs.defs

LOCK=~/emacs-shared/bin/lock-emacs

(
    flock -n 9 || exit 1

    if ! "$CLIENT" -e '"pass"' 2>&1 | grep '"pass"' > /dev/null; then
        echo "Starting Emacs daemon ..."
        "$DAEMON" --daemon
        echo "Starting Emacs daemon ... done"
    fi
) 9>$LOCK

rm -f $LOCK
